stages:
  - build
  - gamma
  - prod

build:
  tags:
    - arch:amd64
    - size:large
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    AWS_CREDS_TARGET_ROLE: arn:aws:iam::464380571579:role/gitlab-caseypl
    AWS_DEFAULT_REGION: us-west-2
    CI_REGISTRY_IMAGE: 464380571579.dkr.ecr.us-west-2.amazonaws.com/cdk-hnb659fds-container-assets-464380571579-us-west-2
  script:
    -  mkdir -p /kaniko/.docker
    -  echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
      --cache=true
      --use-new-run
      --snapshot-mode=redo

unit-test:
  image: node:latest
  stage: build
  script:
    - yarn install
    - npm test

sast:
  stage: build
  image: returntocorp/semgrep
  script:
    - semgrep ci --sarif > gl-sast-report.json
  rules:
    - when: always
  artifacts:
    reports:
      sast: gl-sast-report.json

sca:
  stage: build
  image: 
    entrypoint: [""]
    name: anchore/grype:debug
  script:
    - /grype dir:. -o sarif > gl-dependency-scanning-report.json
  rules:
    - when: always
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

secrets:
  stage: build
  image:
    entrypoint: [""]
    name: zricethezav/gitleaks
  script:
    - gitleaks detect --source . -v -f sarif -r gl-secret-detection-report.json
  rules:
    - when: always
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json

sbom:
  stage: build
  image: 
    entrypoint: [""]
    name: anchore/syft:debug
  script:
    - /syft dir:. -o json > gl-sbom-report.json
  rules:
    - when: always
  artifacts:
    reports:
      cyclonedx: gl-sbom-report.json

deploy-gamma:
  image: node:latest
  stage: gamma
  script:
    - npm install -g aws-cdk
    - yarn install
    - cdk deploy --require-approval never --context tag=${CI_COMMIT_SHA}
  environment:
    name: test
  only:
    - main
  variables:
    AWS_CREDS_TARGET_ROLE: arn:aws:iam::464380571579:role/gitlab-caseypl
    AWS_DEFAULT_REGION: us-west-2
  dependencies:
    - build