stages:
  - build
  - gamma
  - prod

build:
  image: node:latest
  stage: build
  script:
    - yarn install
    - npm run build
  artifacts:
    paths:
      - dist/

unit-test:
  image: node:latest
  stage: build
  script:
    - yarn install
    - npm test

sast:
  stage: build
  image: returntocorp/semgrep
  script:
    - semgrep ci
  rules:
    - when: always
  artifacts:
    reports:
      sast: gl-sast-report.json

sca:
  stage: build
  image: 
    entrypoint: [""]
    name: anchore/grype:debug
  script:
    - /grype dir:. -o sarif > gl-dependency-scanning-report.json
  rules:
    - when: always
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

secrets:
  stage: build
  image: zricethezav/gitleaks
  script:
    - gitleaks detect --source . -v
  rules:
    - when: always
  artifacts:
    reports:
      secret_detection: gl-secret-detection-report.json

sbom:
  stage: build
  image: 
    entrypoint: [""]
    name: anchore/syft:debug
  script:
    - /syft dir:. -o json > gl-sbom-report.json
  rules:
    - when: always
  artifacts:
    reports:
      cyclonedx: gl-sbom-report.json

deploy-gamma:
  image: node:latest
  stage: gamma
  script:
    - npm install -g aws-cdk
    - yarn install
    - cdk deploy --require-approval never
  environment:
    name: test
  only:
    - main
  variables:
    AWS_CREDS_TARGET_ROLE: arn:aws:iam::464380571579:role/gitlab-caseypl
    AWS_DEFAULT_REGION: us-west-2
  dependencies:
    - build